mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('socknet.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

mysite/socknet/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers

from socknet.forms import CustomAuthenticationForm
from socknet.views import api_views, admin_views, author_views, post_views

urlpatterns = [
    # API: Friends
    url(r'^api/friends/(?P<authorid1>[0-9A-Fa-f-]+)/(?P<authorid2>[0-9A-Fa-f-]+)/', api_views.IsFriendQuery.as_view(), name="api_is_friend_query"),
    url(r'^api/friends/(?P<authorid>[0-9A-Fa-f-]+)/$', api_views.FriendsQuery.as_view(), name="api_friend_query"),
    url(r'^api/friendrequest/', api_views.FriendRequest.as_view(), name="api_friend_request"),

    # API: Posts
    url(r'^api/posts/(?P<post_id>[0-9A-Fa-f-]+)/$', api_views.PostIDQuery.as_view(), name="api_posts_id"),
    url(r'^api/posts/$', api_views.PostsQuery.as_view(), name="api_posts"),
    url(r'^api/posts/(?P<post_id>[0-9A-Fa-f-]+)/comments/$', api_views.CommentsViewSet.as_view(), name="api_comments"),
    url(r'^api/images/(?P<img>[0-9A-Fa-f-]+)$', api_views.ViewApiRawImage.as_view(), name='view_api_raw_image'),

    # API: Author
    url(r'^api/author/posts', api_views.AuthorPostsViewSet.as_view(), name="api_author_posts"),
    url(r'^api/author/(?P<auth_id>[0-9A-Fa-f-]+)/posts/$', api_views.AuthorViewAllTheirPosts.as_view(), name="api_authors_posts"),
    url(r'^api/author/(?P<authorid>[0-9A-Fa-f-]+)/$', api_views.ProfileView.as_view(), name="api_profile_view"),

    # Local Posts
    url(r'^$', post_views.ListPosts.as_view(), name='list_posts'),
    url(r'^posts/(?P<pk>[0-9A-Fa-f-]+)/$', post_views.ViewPost.as_view(), name='view_post'),
    url(r'^posts/create/$', post_views.CreatePost.as_view(), name='create_post'),
    url(r'^posts/(?P<pk>[0-9A-Fa-f-]+)/delete/$', post_views.DeletePost.as_view(), name='author_check_delete'),
    url(r'^posts/(?P<pk>[0-9A-Fa-f-]+)/update/$', post_views.UpdatePost.as_view(), name='author_check_update'),

    # Remote Posts
    url(r'^remote_posts/$', post_views.ListRemotePosts.as_view(), name='list_remote_posts'),
    url(r'^remote_node/(?P<nodeID>[0-9]+)/remote_posts/(?P<pk>[0-9A-Fa-f-]+)/$', post_views.ViewRemotePost.as_view(), name='view_remote_post'),

    # Friends Posts (both local and remote)
    url(r'^friends_posts/$', post_views.ListFriendsPosts.as_view(), name='list_friends_posts'),

    # Comments
    url(r'^comment/(?P<pk>[0-9A-Fa-f-]+)/$', post_views.ViewComment.as_view(), name='view_comment'),
    url(r'^posts/(?P<post_pk>[0-9A-Fa-f-]+)/comments/create/$', post_views.CreateComment.as_view(), name='create_comment'),
    url(r'^remote_posts/(?P<pk>[0-9A-Fa-f-]+)/remote-node/(?P<nodeID>[0-9]+)/comments/create/$', post_views.CreateForeignComment.as_view(), name='create_foreign_comment'),

    # Images
    url(r'^images/(?P<img>[0-9A-Fa-f-]+)$', post_views.ViewImage.as_view(), name='view_image'),
    # Redirect static access through Authentication first.
    url(r'^media/(?P<img>[0-9A-Fa-f-]+)$', post_views.raw_image_serve, name='view_raw_image'),

    # Local Profile
    url(r'^profile/(?P<authorUUID>[0-9A-Fa-f-]+)/$', author_views.ViewProfile.as_view(), name='profile'),
    url(r'^edit_profile/(?P<authorUUID>[0-9A-Fa-f-]+)/$', author_views.EditProfile.as_view(), name='editprofile'),

    # Remote Profile
    url(r'^remote_node/(?P<nodeID>[0-9]+)/remote_profile/(?P<authorUUID>[0-9A-Fa-f-]+)/$', author_views.ViewRemoteProfile.as_view(), name='remote_profile'),

    # Friend Management
    url(r'^friends/(?P<authorUUID>[0-9A-Fa-f-]+)/$', author_views.ManageFriends.as_view(), name='manage_friends'),
    url(r'^following/(?P<authorUUID>[0-9A-Fa-f-]+)/$', author_views.ManageFollowing.as_view(), name='manage_following'),
    url(r'^friend_requests/(?P<authorUUID>[0-9A-Fa-f-]+)/$', author_views.ManageFriendRequests.as_view(), name='manage_friend_requests'),

    #  Authentication
    url(r'^login/$', auth_view.login, {'authentication_form': CustomAuthenticationForm}, name='login'),
    url(r'^logout/$', auth_view.logout, {'next_page': '/login/'}, name='logout'),
    url(r'^register/$', admin_views.RegistrationView.as_view(), name='registration'),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# ^ static() This helper function works only in debug mode, and only if the given prefix is local and not an URL.
# https://docs.djangoproject.com/en/1.10/howto/static-files/#serving-uploaded-files-in-development

mysite/socknet/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from socknet.utils import HTMLsafe, AuthorInfo
from django.contrib.postgres.fields import ArrayField
# for images auto delete
from django.db.models.signals import pre_delete
from django.dispatch import receiver
import uuid
from itertools import chain
from socknet.utils import is_FOAF_local

class Node(models.Model):
    """
    Represents a server we can communicate with
    """
    name = models.CharField(max_length=32) # A name for a host. (Ex) socknet
    url = models.URLField(unique=True)
    # user to use for node to use this account as basicauth.
    foreignUserAccessAccount = models.OneToOneField(User)
    # String UserID and Password to access foreign node via basic auth
    foreignNodeUser = models.CharField(max_length=256, null=True)
    foreignNodePass = models.CharField(max_length=256, null=True)

    def __str__(self):
        return self.name

class ForeignAuthor(models.Model):
    """
    Represents an author from another node
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    # Store display name because its needed in lots of places, update it whenever we grab the profile.
    display_name=models.CharField(max_length=150, default='test')
    node = models.ForeignKey(Node, related_name="my_node")
    url = models.URLField(default='')
    #host = models.URLField(default ='')

    def __str__(self):
        return self.display_name

class Author(models.Model):
    """
    Represents an author

    Friends, followers, and friend Requests need to be designed such that:
    - Querying for friends or followers is quick
    - Friends of friends is easy to compute
    - It is easy to decline friend requests
    - Querying pending friend requests is quick
    """
    user = models.OneToOneField(User)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False)

    # Friends and followers are separate --> I can be both a friend and a follower
    # ignored is for friend requests you have declined, just means it won't show up as pending
    friends = models.ManyToManyField("self", related_name="my_friends", blank=True)
    who_im_following = models.ManyToManyField("self", related_name="my_followers", symmetrical=False, blank=True)
    ignored = models.ManyToManyField("self", related_name="ignored_by", symmetrical=False, blank=True)

    # Friend stuff for forgein authors
    foreign_friends = models.ManyToManyField(ForeignAuthor, related_name="my_foreign_friends", blank=True)
    pending_foreign_friends = models.ManyToManyField(ForeignAuthor, related_name="my_pending_foreign_friend_requests", blank=True)
    foreign_friends_im_following = models.ManyToManyField(ForeignAuthor, related_name="foreign_friends_im_following", blank=True)

    # Profile fields
    github_url = models.URLField(blank=True)
    about_me = models.CharField(max_length=1000, blank=True)
    birthday = models.DateField(null=True,blank=True)
    displayName = models.CharField(max_length=150, blank=True)
    url = models.URLField(blank=True)
    host = models.URLField(default='')

    def __str__(self):
        return self.user.get_username()

    def get_site(self):
        # Get the url for the author
        return Site.objects.get_current().domain


    def is_friend(self, author_uuid):
        """
        Checks if an author is this author's friend.
        Checks both local and foreign friend lists.
        """
        is_friend = self.friends.filter(uuid=author_uuid).exists()
        if not is_friend:
            # If author is not a local friend, check if they are a foreign friend
            is_friend = self.foreign_friends.filter(id=author_uuid).exists()
        return is_friend

    def get_pending_local_friend_requests(self):
        """
        Returns all pending local authors
        """
        local_pending = self.my_followers.all()
        local_pending = local_pending.exclude(pk__in=self.ignored.all()) # ignored requests we have declined
        local_pending = local_pending.exclude(pk__in=self.friends.all()) # ignored people we are already friends with
        return local_pending

    def get_pending_friend_requests(self):
        """
        Returns an array of AuthorInfo objects containing the pending friend request information (both local and foreign authors)
        """
        all_pending = []
        local_pending = self.get_pending_local_friend_requests()
        for author in local_pending:
            all_pending.append(AuthorInfo(author.displayName, "Local", author.uuid, True))
        for author in self.pending_foreign_friends.all():
            all_pending.append(AuthorInfo(author.display_name, author.node.name, author.id, False))
        all_pending.sort(key=lambda x: x.name.lower())
        return all_pending

    def get_friends(self):
        """
        Returns an array of AuthorInfo objects containing the all friend information (both local and foreign authors)
        """
        all_friends = []
        for author in self.friends.all():
            # Local friends
            all_friends.append(AuthorInfo(author.displayName, "Local", author.uuid, True))
        for author in self.foreign_friends.all():
            all_friends.append(AuthorInfo(author.display_name, author.node.name, author.id, False))
        all_friends.sort(key=lambda x: x.name.lower())
        return all_friends

    def get_friend_models(self):
        return self.friends

    def get_pending_friend_request_count(self):
        return len(self.get_pending_friend_requests())

    def accept_friend_request(self, requester_uuid, is_local):
        """
        Local behaviour: When a friend request is accepted,
        both authors will be considered followers AND friends of each other.
        """
        if is_local:
            requester = Author.objects.get(uuid=requester_uuid)
            if requester not in self.my_followers.all():
                # Stale state, should probably reload the page
                raise ValueError("Attempted to accept friend request when requester is no longer following me!")
            if requester not in self.friends.all():
                self.friends.add(requester)
            if requester not in self.who_im_following.all():
                self.who_im_following.add(requester)
            if requester in self.ignored.all():
                # If we had them ignored previously, we are friends now
                self.ignored.remove(requester)
        else:
            requester = ForeignAuthor.objects.get(id=requester_uuid)
            if requester not in self.foreign_friends.all():
                self.foreign_friends.add(requester)
            if requester in self.pending_foreign_friends.all():
                self.pending_foreign_friends.remove(requester)
            if requester in self.foreign_friends_im_following.all():
                # Incase the other group does something weird..
                self.foreign_friends_im_following.remove(requester)
        self.save()
        return

    def decline_friend_request(self, requester_uuid, is_local):
        """
        Local behaviour: When we decline a friend request we simply move the requester into
        our ignored queue (all this means is it won't show up in our friend requests).
        Foreign behaviour: Delete from pending foreign friend requests.
        """
        if is_local:
            requester = Author.objects.get(uuid=requester_uuid)
            self.ignored.add(requester)
        else:
            requester = ForeignAuthor.objects.get(id=requester_uuid)
            self.pending_foreign_friends.remove(requester)
        self.save()
        return

    def delete_friend(self, friend, is_local):
        """
        Deletes both local and foreign friends.
        Local: When we remove a friend, we unfriend and unfollow them.
        """
        if is_local:
            # Remove a local friend
            self.friends.remove(friend)
            self.who_im_following.remove(friend)
        else:
            # Remove a foreign friend
            self.foreign_friends.remove(friend)
        self.save()
        return

    def follow(self, friend):
        # Local authors only
        self.who_im_following.add(friend)
        if friend in self.ignored.all():
            # If we had them ignored previously, we are following them now
            self.ignored.remove(friend)
        self.save()

    def unfollow(self, friend):
        # Local authors only
        self.who_im_following.remove(friend)
        self.save()

    def get_following_only(self):
        """ Get who I am following excluding friends (local only)"""
        following = self.who_im_following.all()
        following = following.exclude(pk__in=self.friends.all())
        return following

    def get_all_friend_uuids(self):
        """
        Returns a list all of the authors local and foreign friend uuids.
        """
        local_uuids = [friend.uuid for friend in self.friends.all()]
        foreign_uuids = [friend.id for friend in self.foreign_friends.all()]
        return local_uuids + foreign_uuids

class Post(models.Model):
    """ Represents a post made by a user """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    author = models.ForeignKey(Author, related_name="author")
    title = models.CharField(max_length=64, default="No Title")
    description = models.CharField(max_length=128, default="No description provided.")
    content = models.TextField(max_length=512)
    created_on = models.DateTimeField(auto_now=True)
    markdown = models.BooleanField()
    #imglink = models.CharField(max_length=256)
    imglink = models.UUIDField(editable=True, null=True)
    visibility = models.CharField(default='PUBLIC', max_length=255, choices=[
        ('PUBLIC', 'PUBLIC'),
        ('FOAF', 'FOAF'),
        ('FRIENDS', 'FRIENDS'),
        ('PRIVATE', 'PRIVATE'),

mysite/socknet/views/admin_views.py
from django.views import generic
from django.contrib import messages

from socknet.forms import RegistrationForm

class RegistrationView(generic.edit.FormView):
    template_name = "registration/registration.html"
    form_class = RegistrationForm
    success_url = '/login/'

    def form_valid(self, form):
        form.save()
        # Display a notification
        messages.add_message(self.request, messages.SUCCESS, "Registration Successful. An administrator will approve you account.")
        return super(RegistrationView, self).form_valid(form)

mysite/socknet/templates/socknet/post_templates/author_check_delete.html
{% extends "base.html" %}
{% block content %}
	{% if user.author.uuid == post.author.uuid %}
		<form action="" method="post">{% csrf_token %}
			<div class="content-box">
		    	<p>Are you sure you want to delete post "{{ post.id }}"?</p>
		    	<input type="submit" value="Confirm" />
			</div>
		</form>
	{% else %}
		<center><h2>Unable to delete this post. You are not this post's author.</h2></center>
		{{ deny|safe }}
	{% endif %}
{% endblock %}

mysite/socknet/templates/socknet/post_templates/author_check_update.html
{% extends "base.html" %}
{% block content %}
	{% if user.author.uuid == post.author.uuid %}
	<div class="content-box">
		<h1>Update Post</h1>
		<!-- TODO: Prefill visibility, markdown, and image -->
		<form action="" method="post">{% csrf_token %}
			<div class="form-group">
	        <label for="title">Title</label>
	        <input name="title" type="text" class="form-control" maxLength=64 autofocus="true" required="true" value='{{ post.title }}'>
	    </div>
	    <div class="form-group">
	        <label for="description">Description</label>
	        <input name="description" type="text" class="form-control" maxLength=128 required="true" value='{{ post.description }}'>
	    </div>
	    <label for="content">Content</label>
	    <div class="content-options">
			{% if post.markdown == True %}
	        	<div id="markdown-btn" class="btn btn-default"  style="background-color: #E6E6E6;">
            	<input id="id_markdown" name="markdown" type="checkbox"  style="display: none;" checked="checked"/>
			{% else %}
				<div id="markdown-btn" class="btn btn-default" style="background-color: white;">
				<input id="id_markdown" name="markdown" type="checkbox"  style="display: none;"/>
			{% endif %}
	            Markdown
	        </div>
	        <select id="visibility-select" class="selectpicker" name="visibility">
	          <option value="PUBLIC" selected>Public</option>
	          <option value="FOAF">Friends of Friends</option>
	          <option value="FRIENDS">Friends</option>
	          <option value="PRIVATE">Private</option>
	          <option value="SERVERONLY">Server Only</option>
	        </select>
	        <label class="btn btn-default">
	            Attach New Image <input id="id_image" type="file" name="image" style="display: none;">
	        </label>
	        <!-- Fill in the filename when a file is selected -->
	        <span id="filename"></span>
	    </div>
	    <textarea name="content" class="form-control text-area" type="text" maxLength="512" required="true">{{ post.content }}</textarea>
	    <input type="submit" value="Finish"/>
		</form>
	</div>
	{% else %}
		<center><h2>Unable to edit this post. You are not this post's author.</h2></center>
		{{ deny|safe }}
	{% endif %}
{% endblock %}
{% block scripts %}
<script type="text/javascript">
    $('#id_image').change(function(){
        // Inform the user when a file has been selected
		// From: http://stackoverflow.com/questions/6365858/use-jquery-to-get-the-file-inputs-selected-filename-without-the-path
        var filename = $('#id_image').val().split('\\').pop();
        $('#filename').text(filename)
    });

    $('#markdown-btn').click(function () {
        var checked = $('#id_markdown').prop('checked');
        if (checked) {
            // Change to white and uncheck
            $('#markdown-btn').css("background-color", "white")
            $('#id_markdown').prop('checked', false)
        } else {
            // Change to grey and checked
            $('#markdown-btn').css("background-color", "#E6E6E6")
            $('#id_markdown').prop('checked', true)
        }
    });

		$(document).ready(function() {
			$('#visibility-select').val('{{ post.visibility }}');
		});

</script>
{% endblock scripts %}

mysite/socknet/templates/socknet/post_templates/comment.html
{% extends "base.html" %}
{% block content %}
  <h1>Parent Post id: {{parent-id}} Comment Id: {{comment.id}} parent-id {{comment.parent_post.id}}</h1>
  <p class="authordate">
    Author: {{comment.author.displayName}}<br/>
    Created On (UTC): {{comment.created_on}}
  </p>
  <article class="content">{{comment.view_content|safe}}</article>
  <a href=" url 'list_comments' post_pk=parent_id  ">Return to Post List</a>
{% endblock %}

mysite/socknet/templates/socknet/post_templates/create_comment.html
{% extends "base.html" %}
{% block content %}
<div class="content-box">
<h1>Add Comment</h1>
<form method="post">
    {% csrf_token %}
    <div class="content-options">
        <div id="markdown-btn" class="btn btn-default">
            <input id="id_markdown" name="markdown" type="checkbox"  style="display: none;"/>
            Markdown
        </div>
    </div>
    <textarea name="content" class="text-area" type="text" maxLength="512" required="true"></textarea>
    <input type="submit" value="Finish"/>
</form>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
    $('#markdown-btn').click(function () {
        var checked = $('#id_markdown').prop('checked');
        if (checked) {
            // Change to white and uncheck
            $('#markdown-btn').css("background-color", "white")
            $('#id_markdown').prop('checked', false)
        } else {
            // Change to grey and checked
            $('#markdown-btn').css("background-color", "#E6E6E6")
            $('#id_markdown').prop('checked', true)
        }
    });
</script>
{% endblock scripts %}

mysite/socknet/templates/socknet/post_templates/create_foreign_comment.html
{% extends "base.html" %}
{% block content %}
<div class="content-box">
<h1>Add Comment</h1>
{{foreign_pid}}
{{foreign_node.url}}
<form method="post" >
    {% csrf_token %}
    <div class="content-options">
        <div id="markdown-btn" class="btn btn-default">
            <input id="id_markdown" name="markdown" type="checkbox"  style="display: none;"/>
            Markdown
        </div>
    </div>
    <textarea name="comment" class="text-area" type="text" maxLength="512" required="true"></textarea>
    <input type="submit" value="Finish"/>
</form>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
    $('#markdown-btn').click(function () {
        var checked = $('#id_markdown').prop('checked');
        if (checked) {
            // Change to white and uncheck
            $('#markdown-btn').css("background-color", "white")
            $('#id_markdown').prop('checked', false)
        } else {
            // Change to grey and checked
            $('#markdown-btn').css("background-color", "#E6E6E6")
            $('#id_markdown').prop('checked', true)
        }
    });
</script>
{% endblock scripts %}

mysite/socknet/templates/socknet/post_templates/create_post.html
{% extends "base.html" %}
{% block content %}
<div class="content-box">
<h1>Create Post</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label for="title">Title</label>
        <input name="title" type="text" class="form-control" maxLength=64 autofocus="true" required="true">
    </div>
    <div class="form-group">
        <label for="description">Description</label>
        <input name="description" type="text" class="form-control" maxLength=128 required="true">
    </div>
    <label for="content">Content</label>
    <div class="content-options">
        <div id="markdown-btn" class="btn btn-default">
            <input id="id_markdown" name="markdown" type="checkbox"  style="display: none;"/>
            Markdown
        </div>
        <select id="visibility-select" class="selectpicker" name="visibility">
          <option value="PUBLIC" selected>Public</option>
          <option value="FOAF">Friends of Friends</option>
          <option value="FRIENDS">Friends</option>
          <option value="PRIVATE">Private</option>
          <option value="SERVERONLY">Server Only</option>
        </select>
        <label class="btn btn-default">
            Attach Image <input id="id_image" type="file" name="image" style="display: none;">
        </label>
        <!-- Fill in the filename when a file is selected -->
        <span id="filename"></span>
    </div>
    <textarea name="content" class="form-control text-area" type="text" maxLength="512" required="true"></textarea>
    <input type="submit" value="Finish"/>
</form>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
    $('#id_image').change(function(){
        // Inform the user when a file has been selected
        // From http://stackoverflow.com/questions/6365858/use-jquery-to-get-the-file-inputs-selected-filename-without-the-path
        var filename = $('#id_image').val().split('\\').pop();
        $('#filename').text(filename)
    });

    $('#markdown-btn').click(function () {
        var checked = $('#id_markdown').prop('checked');
        if (checked) {
            // Change to white and uncheck
            $('#markdown-btn').css("background-color", "white")
            $('#id_markdown').prop('checked', false)
        } else {
            // Change to grey and checked
            $('#markdown-btn').css("background-color", "#E6E6E6")
            $('#id_markdown').prop('checked', true)
        }
    });
</script>
{% endblock scripts %}

mysite/socknet/templates/socknet/post_templates/friends_posts.html
{% extends "base.html" %}
{% block content %}
    <ol class="feed">
        {% for post in posts_list %}
            <li class="post">
                <!-- There are different links for viewing a local and remote post-->
                {% if post.is_local %}
                    <div class="first-line">
                        <a href="{% url 'view_post' pk=post.id %} ">
                            <h3>{{ post.title }}</h3>
                        </a>
                    </div>
                {% else %}
                    <div class="first-line">
                        <a href="{% url 'view_remote_post' nodeID=post.node.id pk=post.id %} ">
                            <h3>{{ post.title }}</h3>
                        </a>
                    </div>
                {% endif %}
                <div class="post-id-label">
                    {{ post.visibility }} post submitted by
                    <!-- There are different links for viewing the author is author is local vs. remote -->
                    {% if post.is_local %}
                        <a class="author-label" href="{% url 'profile' authorUUID=post.author_id %}">{{ post.author_display_name }}</a>
                        on {{ post.published }} from <span class="server-label">local</span>
                    {% else %}
                        <a class="author-label" href="{% url 'remote_profile' nodeID=post.node.id authorUUID=post.author_id %}">{{ post.author_display_name }}</a>
                        on {{ post.published }} from <span class="server-label">{{ post.node.name }}</span>
                    {% endif %}
                </div>
                <div class="post-description">
                    {{post.description}}
                </div>
                <article class="content">
                    {{post.content|safe}}
                </article>
                <div>
                    <!-- There are different links for viewing the comments on a local and remote post -->
                    {% if post.is_local %}
                        <a href="{% url 'view_post' pk=post.id %} ">View Comment</a>
                    {% else %}
                        <a href="{% url 'view_remote_post' nodeID=post.node.id pk=post.id %} ">View Comment</a>
                    {% endif %}
                </div>
            </li>
        {% endfor %}
    </ol>
    {% if not posts_list %}
        <div class="content-box">
            <h2>No friends posts to display :(</h2>
        </div>
    {% endif %}
{% endblock %}

mysite/socknet/templates/socknet/post_templates/image.html
{% extends "base.html" %}
{% block content %}
<div class="image-container">
Image: {{image_id}}<br/>
Uploaded by {{image_usr}} on {{image_made}} UTC.<br/>
<a onclick="window.history.back()" href="#">Go Back</a>
  <p id='imgcon'>
      <img id='theimage' src={{b64}} style="max-width:100%;">
  </p>
</div>
{% endblock %}

mysite/socknet/templates/socknet/post_templates/list_comments.html
{% extends "base.html" %}
{% block content %}
    <h2>Comments for Post{{parent.id}}</h2>
    <div class="post-actions">
        <div class="action">
            <a href="{% url 'view_post' pk=parent.id %}">View Post</a>
        </div>
        <div class="action">
            <a href="{% url 'create_comment' post_pk=parent.id %}">New Comment</a>
        </div>
    </div>
    <ol class="feed">
        {% for comment in comments %}
          <li class="post">
            <!--<a href="{{ comment.get_absolute_url }}">View Comment</a>-->
            <div>
                <a class="author-label" href="{% url 'profile' authorUUID=comment.author.uuid %}">{{ comment.author.displayName }}</a>
            </div>
            <div>
              <a class="post-id-label" name="{{ comment.id }}" href="#{{ comment.id }}"># {{ comment.id }}</a>
          </div>
            <div class="author-date">
                {{ comment.created_on }} UTC
            </div>
            <article class="content">
            	{{comment.view_content|safe}}
            </article>
          </li>
        {% endfor %}
    </ol>
    {% if comments.count < 1 %}
    <div class="content-box">There are no comments on this post.</div>
    {% endif %}
{% endblock %}

mysite/socknet/templates/socknet/post_templates/list_posts.html
{% extends "base.html" %}
{% block content %}
    <ol class="feed">
        {% for post in posts_list %}
            <li class="post">
                {% include "socknet/post_templates/subtemplate_post.html" %}
                <div class="post-actions">
                    <div class="action">
                        <a href="{% url 'view_post' pk=post.pk %}">View Comments</a>
                    </div>
                    <div class="action">
                        <a href="{% url 'create_comment' post_pk=post.pk %}">Write Comment</a>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ol>
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="/?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="/?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock %}